# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: bot deployment flow

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/**
      - bot/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Test build
    - uses: actions/setup-node@v3
      with:
        node-version: 14
        cache: 'npm'
        cache-dependency-path: bot/package-lock.json
    - run: cd bot \
           npm ci \
           npm run build --if-present \
           npm test --if-present \


