name: bot deployment flow

on:
  push:
    branches: [ "main" ]
    paths:
      - .github/workflows/**
      - bot/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
        cache-dependency-path: bot/package-lock.json
    - run: | 
        cd bot 
        npm ci 
        npm run build --if-present 
        npm run test --if-present



